apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = false
      logfile = "telegraf.log"
      hostname = ""
      omit_hostname = true
    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "telegraf"
      username = "admin"
      password = "password"
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_name_include = []
      timeout = "5s"
      perdevice = true
      total = true
      docker_label_include = []
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: telegraf-config
              subPath: telegraf.conf
              mountPath: /etc/telegraf.conf
              readOnly: true
            - name: docker-unix-socket
              mountPath: /var/run/docker.sock
          envFrom:
            - secretRef:
                name: influxdb-secret
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: docker-unix-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
